-- Agrega el catalogo curricular oficial sin borrar materias historicas ni sus relaciones.
INSERT INTO materias (nombre)
SELECT catalogo.nombre
FROM (
    SELECT 'Análisis Matemático' AS nombre
    UNION ALL SELECT 'Arte'
    UNION ALL SELECT 'Biología'
    UNION ALL SELECT 'Ciencia, tecnología y Sociedad'
    UNION ALL SELECT 'Ciencias Naturales'
    UNION ALL SELECT 'Ciencias Sociales'
    UNION ALL SELECT 'Conocimiento de los Materiales'
    UNION ALL SELECT 'Construcción de Ciudadanía'
    UNION ALL SELECT 'Construcción Ciudadana'
    UNION ALL SELECT 'Derecho del Trabajo'
    UNION ALL SELECT 'Derechos del trabajo'
    UNION ALL SELECT 'Desarrollo de productos de mobiliario'
    UNION ALL SELECT 'Dibujo Tecnológico'
    UNION ALL SELECT 'Diseño y Fabricación'
    UNION ALL SELECT 'Diseño y Montaje de Estructuras Mecánicas'
    UNION ALL SELECT 'Diseños y prototipos de mobiliario'
    UNION ALL SELECT 'Educación Artística'
    UNION ALL SELECT 'Educación Física'
    UNION ALL SELECT 'Electrotecnia'
    UNION ALL SELECT 'Emprendimientos Productivos y Desarrollo Local'
    UNION ALL SELECT 'Ergonomía'
    UNION ALL SELECT 'Fabricación automatizada en Carpintería y Muebles'
    UNION ALL SELECT 'Fabricación de Mobiliario'
    UNION ALL SELECT 'Filosofía'
    UNION ALL SELECT 'Física'
    UNION ALL SELECT 'Físico Química'
    UNION ALL SELECT 'Geografía'
    UNION ALL SELECT 'Historia'
    UNION ALL SELECT 'Historia del diseño y del mobiliario'
    UNION ALL SELECT 'Inglés'
    UNION ALL SELECT 'Instalación de Mobiliario y Estructuras de Madera'
    UNION ALL SELECT 'Instalaciones Eléctricas'
    UNION ALL SELECT 'Instalaciones Industriales'
    UNION ALL SELECT 'Instalaciones Industriales de Carpintería'
    UNION ALL SELECT 'Laboratorio de Ensayos Industriales'
    UNION ALL SELECT 'Lenguajes Tecnológicos'
    UNION ALL SELECT 'Literatura'
    UNION ALL SELECT 'Mantenimiento y Reparación de Equipos, Instalaciones Mecánicas'
    UNION ALL SELECT 'Máquinas Eléctricas'
    UNION ALL SELECT 'Máquinas y Elementos para Maniobra, Elevación y Transporte'
    UNION ALL SELECT 'Materiales y Procesos'
    UNION ALL SELECT 'Matemática'
    UNION ALL SELECT 'Matemática Aplicada'
    UNION ALL SELECT 'Matemática Ciclo Superior'
    UNION ALL SELECT 'Mecánica'
    UNION ALL SELECT 'Mecánica de los Fluidos'
    UNION ALL SELECT 'Mecatrónica'
    UNION ALL SELECT 'Metalurgia y Siderurgia'
    UNION ALL SELECT 'Organización de los Procesos productivos'
    UNION ALL SELECT 'Política y Ciudadanía'
    UNION ALL SELECT 'Prácticas del Lenguaje'
    UNION ALL SELECT 'Prácticas Profesionalizantes de Sector: Mecánico'
    UNION ALL SELECT 'Prácticas Profesionalizantes del Sector de la Madera y el Mueble'
    UNION ALL SELECT 'Procedimientos Técnicos'
    UNION ALL SELECT 'Procesamiento Mecánico'
    UNION ALL SELECT 'Proceso de fabricación de mobiliario'
    UNION ALL SELECT 'Proyecto y Diseño Mecánico'
    UNION ALL SELECT 'Química'
    UNION ALL SELECT 'Resistencia de Materiales y Cálculo de Elementos de Máquina'
    UNION ALL SELECT 'Salud y Adolescencia'
    UNION ALL SELECT 'Seguridad e Higiene y Protección Ambiental'
    UNION ALL SELECT 'Sistemas Mecánicos'
    UNION ALL SELECT 'Sistemas Tecnológicos'
    UNION ALL SELECT 'Tecnología de Control'
    UNION ALL SELECT 'Tecnología de la Representación'
    UNION ALL SELECT 'Tecnología de los Materiales'
    UNION ALL SELECT 'Tecnología Mecánica'
    UNION ALL SELECT 'Tecnologías y soluciones constructivas'
    UNION ALL SELECT 'Termodinámica y Máquinas Térmicas'
    UNION ALL SELECT 'Unión y Conformación de los Materiales'
) AS catalogo
WHERE NOT EXISTS (
    SELECT 1
    FROM materias existente
    WHERE existente.nombre = catalogo.nombre
);